[package]
name = "life"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.22.1"
indexmap = "1.8.0"
itertools = "0.10.3"

[[bin]]
name = "life"
path = "src/main.rs"
